name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run -s typecheck || echo "No typecheck script"

      - name: Lint
        run: npm run -s lint || echo "No lint script"

      - name: Unit Tests
        run: npm run -s test || echo "No tests"

      - name: Build
        run: npm run -s build

      - name: E2E Tests
        run: npm run -s e2e || echo "No e2e tests"